export const ON_API_CALL_FAILURE = 'ON_API_CALL_FAILURE';
export const ON_API_CALL_SUCCESS = 'ON_API_CALL_SUCCESS';
export const SET_CURRENT_STAR_WARS_MOVIE = 'SET_CURRENT_STAR_WARS_MOVIE';
export const SET_IS_LOADING = 'SET_IS_LOADING';
export const SET_STAR_WARS_MOVIE_LIST = 'SET_STAR_WARS_MOVIE_LIST';
export const SET_URL_RESOURCE_CONTENT = 'SET_URL_RESOURCE_CONTENT';
export const SET_URL_RESOURCE_DID_ERROR_OCCUR_WHILE_FETCHING = (
  'SET_URL_RESOURCE_DID_ERROR_OCCUR_WHILE_FETCHING'
);
export const SET_URL_RESOURCE_IS_LOADING = 'SET_URL_RESOURCE_IS_LOADING';
