export const ON_API_CALL_FAILURE = 'ON_API_CALL_FAILURE';
export const ON_API_CALL_SUCCESS = 'ON_API_CALL_SUCCESS';
export const SET_CURRENT_STAR_WARS_MOVIE = 'SET_CURRENT_STAR_WARS_MOVIE';
export const SET_IS_LOADING = 'SET_IS_LOADING';
export const SET_STAR_WARS_MOVIE_LIST = 'SET_STAR_WARS_MOVIE_LIST';
